name: CI

on:
  push:
    tags-ignore:
      - "v*.*.*"

jobs:
  check:
    name: 'Check'
    timeout-minutes: 30
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-checks
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@mementi-io'

      - name: 'Install NPM Dependencies'
        run: 'pnpm install --frozen-lockfile'

      - name: 'Check for Errors'
        run: 'pnpm check'
