name: CI

on: [push]

jobs:
  check:
    name: 'Check'
    timeout-minutes: 30
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-checks
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: 'Install NPM Dependencies'
        run: 'pnpm install --frozen-lockfile --child-concurrency=10'

      - name: 'Check for Errors'
        run: 'pnpm check'
