name: Release

on:
  push:
    tags:
      - "v*.*.*"
    paths-ignore:
      - '*.md'
      - '.editorconfig'
      - '.github/**'
      - 'examples/**'

permissions:
  contents: read
  packages: write

jobs:
  release:
    name: Release
    timeout-minutes: 30
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    if: github.repository_owner == 'mementi-io' && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@mementi-io'

      - name: 'Install NPM Dependencies'
        run: 'pnpm install --frozen-lockfile'

      - name: Check the build
        run: pnpm build

      - name: 'Check for Errors'
        run: 'pnpm check'

      - name: 'Publish to GitHub Packages'
        run: 'pnpm publish'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
