name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    timeout-minutes: 30
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    if: github.repository_owner == 'mementi-io'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@mementi-io'

      - name: 'Install NPM Dependencies'
        run: 'pnpm install --frozen-lockfile'

      - name: Check the build
        run: pnpm build

      - name: 'Check for Errors'
        run: 'pnpm check'

      - name: 'Publish to GitHub Packages'
        run: 'pnpm publish'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
